language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js: 
  - '16'
git:
  depth: 3
script:
  - yarn build
notifications:
  email:
    recipients:
      - jesusrivero19@gmail.com
      - j.manuelrivero@outlook.com
      on_success: always
      on_failure: always
deploy:
  provider: pages
  skip-clean: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit: "Deploy to Project"
  on:
    branch: main

